DATA:
  PROCESSED_ROOT: "/home/pa/version4/data/Teeth_simulation_10K_processed_new_v11"

MODEL:
  BACKBONE:
    NAME: "MiniPointNet"
  STRATEGY:
    NAME: "IdentityGate"         # 门控依然全开
  HEAD:
    POS:
      NAME: "DeterministicHead"
    ROT:
      NAME: "DeterministicHead"
  
  USE_SPATIAL_ATTN: True         # 🟢 开启：牙齿开始物理交互
  USE_TEMPORAL_ATTN: False       # 依然关闭时间感知
  
  D_MODEL: 512
  NHEAD: 8
  NUM_LAYERS: 6
  DROPOUT: 0.1
  NUM_TEETH: 32

TRAIN:
  SAVE_DIR: "/home/pa/version-final/checkpoints_ab02_spatial_new"
  BATCH_SIZE: 32
  NUM_EPOCHS: 300
  STAGE1_EPOCHS: 300
  STAGE2_EPOCHS: 0
  STAGE3_FREEZE_EPOCHS: 0
  LEARNING_RATE: 0.001
  WARMUP_EPOCHS: 15

INFER:
  UNCERTAINTY_SCALE_FACTOR: 0.0
  STOP_THRES_POS: 0.2
  STOP_THRES_DEG: 3.0
  MASK_THRESHOLD: 0.5